chore(#364): Link to bugs tracker and repository
doug-wade/tybalt pull request #430
Opened 2023-08-15 00:02 UTC by Ashvith10

Fixes #364 

PR is in draft to discuss about the repo links for internal packages.

2023-08-15 00:31 UTC, doug-wade requested changes

2023-08-15 00:31 UTC, doug-wade commented on packages/core/package.json
> +    "bugs": { "url" : "https://github.com/doug-wade/tybalt/issues" },
I think this field is meant to be a link to the currently open bugs for this node module, so I think we can link to the tag we maintain for this package: https://github.com/doug-wade/tybalt/issues?q=is%3Aissue+is%3Aopen+label%3Acore

2023-08-15 00:31 UTC, doug-wade commented on packages/core/package.json
> +    "homepage": "https://tybalt.org",
I think we can link to the page specific to each public package's page: https://tybalt.org/pages/core/

2023-08-15 06:44 UTC, Ashvith10 commented on packages/eleventy-plugin-vanilla-example/package.json
> +    "bugs": { "url" : "https://github.com/doug-wade/tybalt/issues" },
@doug-wade what about `eleventy-plugin-vanilla-example`? There's no such label or homepage...

2023-08-15 17:49 UTC, doug-wade requested changes

2023-08-15 17:49 UTC, doug-wade commented on packages/example/package.json
> +    "homepage": "https://tybalt.org/pages/example",
I don't think this page exists; probably https://tybalt.org/ works

2023-08-15 17:49 UTC, doug-wade commented on packages/test-utils-lit-example/package.json
> +    "homepage": "https://tybalt.org/pages/test-utils-lit-example",
I don't think this page exists -- ttps://tybalt.org/pages/test-utils ?

2023-08-20 22:09 UTC, doug-wade commented
We needed this for the release, so I landed it in https://github.com/doug-wade/tybalt/pull/438

2023-08-20 22:09 UTC, closed without merging